"""created model

Revision ID: 45ecaf8f7149
Revises: 4d8a57f13331
Create Date: 2024-01-17 02:33:20.646803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ecaf8f7149'
down_revision = '4d8a57f13331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('PRAGMA foreign_keys=off;')
    op.execute('BEGIN TRANSACTION;')
    op.execute('CREATE TEMPORARY TABLE messages_backup(id, body, username, created_at, updated_at);')
    op.execute('INSERT INTO messages_backup SELECT id, body, username, created_at, updated_at FROM messages;')
    op.execute('DROP TABLE messages;')
    op.execute('CREATE TABLE messages(id INTEGER NOT NULL, body VARCHAR, username VARCHAR, created_at DATETIME, updated_at DATETIME, PRIMARY KEY (id));')
    op.execute('INSERT INTO messages SELECT id, body, username, datetime(created_at, \'unixepoch\'), updated_at FROM messages_backup;')
    op.execute('DROP TABLE messages_backup;')
    op.execute('COMMIT;')
    op.execute('PRAGMA foreign_keys=on;')
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###
