"""create messages table

Revision ID: a0aede9cad6e
Revises: 45ecaf8f7149
Create Date: 2024-01-17 03:52:20.578401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0aede9cad6e'
down_revision = '45ecaf8f7149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
